version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: nexus-db
    environment:
      POSTGRES_DB: nexusdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d nexusdb" ]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: nexus-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nexusdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus-frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: nexus-worker-standalone
    ports:
      - "8084:8084"
    depends_on:
      backend:
        condition: service_healthy

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: nexus-producer
    environment:
      BACKEND_HOST: backend
      PORT: 8080
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
